<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="xiaolanyun" name="com.xiaolanyun.appium.DataTest.testCase.Login.LoginPage_001_UICheckForRootLogin_Test" tests="1" failures="0" timestamp="16 Apr 2019 03:11:19 GMT" time="0.009" errors="1">
  <testcase name="checkUI" time="0.009" classname="com.xiaolanyun.appium.DataTest.testCase.Login.LoginPage_001_UICheckForRootLogin_Test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xiaolanyun.appium.DataTest.utils.AppiumUtil.findElement(AppiumUtil.java:92)
	at com.xiaolanyun.appium.DataTest.utils.AppiumUtil.typeContent(AppiumUtil.java:116)
	at com.xiaolanyun.appium.DataTest.pagesHelper.Mart_LoginPageHelper.clickForRootLogin(Mart_LoginPageHelper.java:42)
	at com.xiaolanyun.appium.DataTest.testCase.Login.LoginPage_001_UICheckForRootLogin_Test.checkUI(LoginPage_001_UICheckForRootLogin_Test.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- checkUI -->
</testsuite> <!-- com.xiaolanyun.appium.DataTest.testCase.Login.LoginPage_001_UICheckForRootLogin_Test -->
